export const SET_CURRENCY_RATES_REQUEST = 'SET_CURRENCY_RATES_REQUEST';
export const SET_CURRENCY_RATES_SUCCESS = 'SET_CURRENCY_RATES_SUCCESS';
export const SET_CURRENCY_RATES_FAIL = 'SET_CURRENCY_RATES_FAIL';