export const CURRENCY_EXCHANGE_RATES_REQUEST = 'CURRENCY_EXCHANGE_RATES_REQUEST';
export const CURRENCY_EXCHANGE_RATES_SUCCESS = 'CURRENCY_EXCHANGE_RATES_SUCCESS';
export const CURRENCY_EXCHANGE_RATES_FAIL = 'CURRENCY_EXCHANGE_RATES_FAIL';